name: Identify
main: com.modcrafting.identify.Identify
version: 1.0
website: http://modcrafting.com
author: Deathmarine
commands:
  identify:
    description: Command Access
    usage: /<command> <help/list/set/buy>