name: Identify
main: com.modcrafting.identify.Identify
version: 0.0.1
website: http://modcrafting.com
author: Deathmarine
description: >
             Buy Plugin for Bukkit.
commands:
  identify:
    description: Command Access
    usage: /<command> - Uses identify function.